networks:
  net:
    driver: bridge
volumes:
  db-persistence:
    driver: local

services:
  rizzavel:
    container_name: rizzavel
    image: rizzavel:1.0.0
    restart: unless-stopped
    ports: ["8080:8080"]
    depends_on:
      database:
        condition: service_healthy
  database:
    container_name: database
    image: mariadb:11.3.2-jammy
    restart: unless-stopped
    volumes: [db-persistence:/var/lib/mysql]
    env_file: [.env]
    environment:
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      interval: 3s
      retries: 5
      start_period: 30s
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.2.1-apache
    restart: unless-stopped
    ports: ["3000:80"]
    depends_on: [database]
    env_file: [.env]
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}

