name: finalsysadmin

volumes:
  dbpersist:
    driver: local

services:
  rizzavel:
    build:
      context: .
      args:
        USER: www
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
  mariadb:
    image: mariadb:11.3.2-jammy
    restart: unless-stopped
    volumes: [dbpersist:/var/lib/mysql]
    env_file: [.env]
    environment:
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized",
        ]
      interval: 3s
      retries: 5
      start_period: 30s
  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    restart: unless-stopped
    depends_on: [mariadb]
    env_file: [.env]
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
  nginx:
    image: nginx:1.27.0-alpine3.19
    restart: unless-stopped
    ports: ["80:80"]
    depends_on: [rizzavel]
    volumes: [./nginx.conf:/etc/nginx/conf.d/default.conf:ro]
